# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweety',
            old_name='text_area',
            new_name='comment',
        ),
    ]
