# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTweety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'/home/hp/Devel/tweetytimor/tweetytimor/tweetytimor/media/', verbose_name='camera')),
            ],
        ),
    ]
