# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0002_auto_20160225_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetcomment',
            old_name='comment',
            new_name='tweetcomment',
        ),
    ]
