# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:18
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0002_persontweety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontweety',
            name='picture',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to='img', verbose_name='camera'),
        ),
    ]
