# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0002_auto_20160212_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweety',
            old_name='comment',
            new_name='description',
        ),
    ]
