# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweety', '0003_auto_20160226_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
