# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:42
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0005_auto_20160404_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontweety',
            name='picture',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to=b'/home/hp/Devel/tweetytimor/tweetytimor/tweetytimor/media/', verbose_name='camera'),
        ),
    ]
