# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweety', '0005_auto_20160301_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='title',
        ),
        migrations.AddField(
            model_name='user_login',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
