# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0006_auto_20160301_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='name',
        ),
    ]
