# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0007_remove_user_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='name',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
