# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0008_auto_20160216_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetytimor',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
