# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0008_user_login_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='name',
        ),
        migrations.AddField(
            model_name='user_login',
            name='first_name',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='last_name',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='password',
            field=models.TextField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='username',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
