# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0009_auto_20160303_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
