# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0009_auto_20160216_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetytimor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
